plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.shuhao.webchromeclient'
    compileSdk  34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    publishing {
        singleVariant("release") {
//            withJavadocJar()
//            withSourcesJar()
        }
    }
}

project.dependencies {
    implementation  fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation ('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.squareup.okhttp3:okhttp:3.3.1'
    implementation 'com.android.support:appcompat-v7:25.3.1'
    testImplementation  'junit:junit:4.13.2'
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.czheji'
            artifactId = 'AndroidWebviewInputFile'
            version = '1.0.0'

            afterEvaluate {
                from components.release
            }
        }
    }
}
